### ISSUE TITLE
TacticianHandler and Command mapping

### ISSUE THREAD

**Issue by simdoor** [AgencyPMG/queue-tactician#6]
Hi there,
I am trying to integrate your great queue package in a project of mine.
However I cannot get my head around the proper use of the TacticianHandler.
I can see from source file that the handle() method creates a new QueuedCommand from each message and then passes it on to the CommandBus.
At this point, I am lost about how to provide the command > commandHandler mapping: all commands will just look the same for the CommandBus.
How would you recommend to get around this problem? Am I just missing something?
Hope you can help, thanks!
Simone

**Comment by chrisguitarguy** [comment]
Hi!

I'm really sorry I didn't see this until now. The gist of it is that you'll need to add the `QueueingMiddleware` to tactician's middleware stack, then use the TacticianHandler with the queue: https://github.com/AgencyPMG/queue-tactician/blob/master/src/Handler/TacticianHandler.php

The middleware will "unpack" the command to it's really object -- it does this so there's loop wehre the message is takend frmo a queue backend then immediately sent back to it.
